# Test LaLigaAPI

# TEST Reading parquet files

In [3]:
# import parquets
import pandas as pd

# Load games from parquet file
games = pd.read_parquet('../data/parquet/games_stats_22_and_23.parquet')
games.tail()

,match_1,match_2,match_3,match_4,match_5,match_6,match_7,match_8,match_9,match_10,matchday
71,"{'date': '2024-05-05T00:00:00.000Z', 'id': 331...","{'date': '2024-05-05T00:00:00.000Z', 'id': 332...","{'date': '2024-05-05T00:00:00.000Z', 'id': 333...","{'date': '2024-05-05T00:00:00.000Z', 'id': 334...","{'date': '2024-05-05T00:00:00.000Z', 'id': 335...","{'date': '2024-05-05T00:00:00.000Z', 'id': 336...","{'date': '2024-05-05T00:00:00.000Z', 'id': 337...","{'date': '2024-05-05T00:00:00.000Z', 'id': 338...","{'date': '2024-05-05T00:00:00.000Z', 'id': 339...","{'date': '2024-05-05T00:00:00.000Z', 'id': 340...",34
72,"{'date': '2024-05-12T00:00:00.000Z', 'id': 341...","{'date': '2024-05-12T00:00:00.000Z', 'id': 342...","{'date': '2024-05-12T00:00:00.000Z', 'id': 343...","{'date': '2024-05-12T00:00:00.000Z', 'id': 344...","{'date': '2024-05-12T00:00:00.000Z', 'id': 345...","{'date': '2024-05-12T00:00:00.000Z', 'id': 346...","{'date': '2024-05-12T00:00:00.000Z', 'id': 347...","{'date': '2024-05-12T00:00:00.000Z', 'id': 348...","{'date': '2024-05-12T00:00:00.000Z', 'id': 349...","{'date': '2024-05-12T00:00:00.000Z', 'id': 350...",35
73,"{'date': '2024-05-15T00:00:00.000Z', 'id': 351...","{'date': '2024-05-15T00:00:00.000Z', 'id': 352...","{'date': '2024-05-15T00:00:00.000Z', 'id': 353...","{'date': '2024-05-15T00:00:00.000Z', 'id': 354...","{'date': '2024-05-15T00:00:00.000Z', 'id': 355...","{'date': '2024-05-15T00:00:00.000Z', 'id': 356...","{'date': '2024-05-15T00:00:00.000Z', 'id': 357...","{'date': '2024-05-15T00:00:00.000Z', 'id': 358...","{'date': '2024-05-15T00:00:00.000Z', 'id': 359...","{'date': '2024-05-15T00:00:00.000Z', 'id': 360...",36
74,"{'date': '2024-05-19T00:00:00.000Z', 'id': 361...","{'date': '2024-05-19T00:00:00.000Z', 'id': 362...","{'date': '2024-05-19T00:00:00.000Z', 'id': 363...","{'date': '2024-05-19T00:00:00.000Z', 'id': 364...","{'date': '2024-05-19T00:00:00.000Z', 'id': 365...","{'date': '2024-05-19T00:00:00.000Z', 'id': 366...","{'date': '2024-05-19T00:00:00.000Z', 'id': 367...","{'date': '2024-05-19T00:00:00.000Z', 'id': 368...","{'date': '2024-05-19T00:00:00.000Z', 'id': 369...","{'date': '2024-05-19T00:00:00.000Z', 'id': 370...",37
75,"{'date': '2024-05-26T00:00:00.000Z', 'id': 371...","{'date': '2024-05-26T00:00:00.000Z', 'id': 372...","{'date': '2024-05-26T00:00:00.000Z', 'id': 373...","{'date': '2024-05-26T00:00:00.000Z', 'id': 374...","{'date': '2024-05-26T00:00:00.000Z', 'id': 375...","{'date': '2024-05-26T00:00:00.000Z', 'id': 376...","{'date': '2024-05-26T00:00:00.000Z', 'id': 377...","{'date': '2024-05-26T00:00:00.000Z', 'id': 378...","{'date': '2024-05-26T00:00:00.000Z', 'id': 379...","{'date': '2024-05-26T00:00:00.000Z', 'id': 380...",38

In [4]:
# Load players from parque file
players = pd.read_parquet('../data/parquet/players_22_and_23.parquet')
players.head()

,images,positionId,nickname,lastSeasonPoints,playerStatus,marketValue,team,points,averagePoints,playerStats,name,slug,position,historicalMarketValues
id,,,,,,,,,,,,,,
53,{'beat': {'1024x1024': 'https://assets-fantasy...,1.0,Oblak,164.0,injured,29745523.0,{'badgeColor': 'https://assets-fantasy.llt-ser...,0.0,0.0,"[{'stats': {'ball_recovery': [4 0], 'effective...",Jan Oblak,oblak,Portero,"[{'bids': 0, 'date': '2023-07-13T00:00:00+02:0..."
68,{'beat': {'1024x1024': 'https://assets-fantasy...,1.0,Unai Simón,166.0,ok,27738350.0,{'badgeColor': 'https://assets-fantasy.llt-ser...,0.0,0.0,"[{'stats': {'ball_recovery': [9 1], 'effective...",Unai Simón Mendibil,unai,Portero,"[{'bids': 0, 'date': '2023-07-13T00:00:00+02:0..."
93,{'beat': {'1024x1024': 'https://assets-fantasy...,1.0,Ter Stegen,284.0,ok,53294805.0,{'badgeColor': 'https://assets-fantasy.llt-ser...,0.0,0.0,"[{'stats': {'ball_recovery': [8 1], 'effective...",Marc-André Ter Stegen,ter-stegen,Portero,"[{'bids': 0, 'date': '2023-07-13T00:00:00+02:0..."
140,{'beat': {'1024x1024': 'https://assets-fantasy...,1.0,Iván Villar,85.0,ok,4992637.0,{'badgeColor': 'https://assets-fantasy.llt-ser...,0.0,0.0,"[{'stats': {'ball_recovery': [0 0], 'effective...",Iván Villar,ivan-villar,Portero,"[{'bids': 0, 'date': '2023-07-13T00:00:00+02:0..."
184,{'beat': {'1024x1024': 'https://assets-fantasy...,1.0,David Soria,237.0,ok,20050462.0,{'badgeColor': 'https://assets-fantasy.llt-ser...,0.0,0.0,"[{'stats': {'ball_recovery': [8 1], 'effective...",David Soria Solís,soria-david,Portero,"[{'bids': 0, 'date': '2023-07-13T00:00:00+02:0..."